config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'homes/top'
  end
    # 顧客用
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  devise_scope :customer do
    get '/customers', to: 'public/registrations#new'
  end
  # 管理者用
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
  root to: 'public/homes#top'
  scope module: :public do
    get '/about' => 'homes#about'
    get '/thanks' => 'homes#thanks'
    get '/privacy_policy' => 'homes#privacy'

    # 「customers」
    get '/customers/my_page' => 'customers#show', as: 'my_page'
    get '/customers/information/edit' => 'customers#edit', as: 'customers_edit'
    patch '/customers/information' => 'customers#update', as: 'information'
    get '/customers/unsubscribe' => 'customers#unsubscribe', as: 'unsubscribe'
    patch '/customers/withdraw' => 'customers#withdraw', as: 'withdraw'
    get '/routines/bookmark' => 'routines#like', as: 'bookmark'
    get '/routines/heatmap' => 'routines#heatmap'


    resources :routines do
      resources :sub_task_commits
      resources :task_commits
    end
    resources :bookmarks, only: [:create, :destroy, :index]

    resources :routines, except: [:index] do
      resource :bookmarks, only: [:create, :destroy, :index, :like]
    end


  end
  #####################
  # 管理者側のルーティング設定
  ## URLの頭に「admin」入れる設定
  namespace :admin do
    root to: 'homes#top'
    resources :routines, :customers

  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile_image

  has_many :routines, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :bookmark_routines, through: :bookmarks, source: :routine
  validates :nickname, {length:{maximum:10} }

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image01.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'no_image01.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.all.order("created_at DESC").page(params[:page]).per(8)
  end

  def show
    @customer = Customer.find(params[:id])
    @routines = @customer.routines.order("created_at DESC").page(params[:page])
    @current_routines = []
    @backnumber_routines = []
    current_daytime = Time.current
    @routines.find_each do |routine|
      # created_at + period <=> current_day
      if routine.created_at.since(Period::TASK_DURATION_TABLE[routine.period.period.to_sym]).after?(current_daytime)
        @current_routines << routine
      else
        @backnumber_routines << routine
      end
    end
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
    # 更新に成功したときの処理
      flash[:notice]="更新完了しました！"
      redirect_to admin_customer_path(@customer.id)
    else
      render :edit
    end
  end
  def destroy
    @customer = Customer.find(params[:id])
		#is_deletedカラムにフラグを立てる(defaultはfalse)
    @customer.destroy
    #ログアウトさせる
    flash[:notice] = "会員の削除が完了いたしました。"
    redirect_to admin_customers_path
  end

  private
  def customer_params
    params.require(:customer).permit(:email, :customer_id, :profile_image, :nickname, :is_deleted, :created_at, :updated_at)
  end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="admin-customer-wrapper">
  <div class="admin-customer-edit-contents">
    <h5>■会員情報編集</h5>
    <div class="customer-edit-form">
      <%= form_with model: @customer ,url: admin_customer_path(@customer.id),method: :patch do |f| %>
      <div>
        <p class="edit-label"><b><%= f.label :'プロフィール画像' %></b></p>
        <p><%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %></p>
      </div>
      <!--氏名-->
      <div>
        <p class="edit-label"><b><%= f.label :'ニックネーム' %></b></p>
        <div>
          <%= f.text_field :nickname, autofocus: true, autocomplete: "last_name", placeholder: "ジョン・タイター", class: "form-control" %>
        </div>
      </div>
      <!--メールアドレス-->
      <div>
        <p class="edit-label"><b><%= f.label :メールアドレス %></b></p>
        <div>
          <%= f.email_field :email, autocomplete: "email", class: "form-control" %>
        </div>
      </div>
      <!--ボタン-->
      <div class="btns">
        <%= f.submit'変更', class: "update-btn" %>
        <%= link_to '戻る' , admin_customer_path(@customer.id), class: "update-btn" %>
      </div>
      <%= link_to "アカウント削除する", admin_customer_path(@customer.id), method: :delete, "data-confirm" => "本当に削除しますか？", class:"text-danger" %>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div class="admin-customer-wrapper">
  <h5>■会員情報一覧</h5>
  <div class="item-contents_all">
    
  <% @customers.each do |customer| %>
  <%= link_to admin_customer_path(customer.id) do %>
    <div class="item-contents3">
      <div class="item-content3">
        <p><b>ニックネーム</b><br><%= customer.nickname %></p>
        <% if customer.profile_image.attached? %>
          <div style="text-align: center;" class="profile-icon"><%= image_tag customer.profile_image, size: "50x50" %></div>
        <% else %>
          <div style="text-align: center;" class="profile-icon"><%= image_tag 'no_image.png', size: "50x50" %></div>
        <% end %>
        <p><b>登録日</b><br><%= l customer.created_at %></p>
      </div>
    </div>
  <% end %>
  <% end %>
  </div>
  <div class="pagenate_content">
    <%= paginate @customers %>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="my-page-wrapper">
  <h5>■<%= @customer.nickname %>&ensp;さんのマイページ</h5>
  <div class="my-page-contents">
    <!--プロフィー部分-->
    <div class="my-page-left">
      <div class="profile-contents">
        <% if @customer.profile_image.attached? %>
        <div style="text-align: center;"><%= image_tag @customer.profile_image, size: "100x00" %></div>
        <% else %>
        <div style="text-align: center;"><%= image_tag 'no_image.png', size: "100x100" %></div>
        <% end %>
        <p><%= link_to "プロフィールを編集" ,edit_admin_customer_path, class:"prof-edit-btn" %></p>
      </div>
    </div>

    <div class="my-page-right">
      <div>
        <div class="my-page-right-txt">
          <h5>■Routine一覧</h5>
        </div>
        <div class="item-contents_all">
          <% @current_routines.each do |routine| %>
          <%= link_to edit_admin_routine_path(routine.id) do %>
          <div class="item-contents2">
            <div class="status_tag_routine">
              <%if routine.public_status %>
                <span class="item-check"><i class="fa-solid fa-lock-open"></i></span>
              <% else %>
                <span class="item-lock"><i class="fa-solid fa-lock"></i></span>
              <% end %>
            </div>
            <p class="create_at_tag"><%= l routine.created_at %></p>
            <div class="item-content">
              <ul>
                <li><b>目標</b><br><p><%= routine.target %></p></li>
                <li><b>ルーティン</b><br><p><%= routine.task.name %></p></li>
                <li class="sub_task_list">
                  <p>
                  <% routine.task.sub_tasks.each do | sub_task| %>
                    <span class="subtask_line"><%= sub_task.name %></span>
                  <% end %>
                  </p>
                </li>
                <li class="time-list">
                  <span class="item-content-title"><b>時間</b>:
                  <% if routine.implementation_time.accurate_time.present? %>
                    <%= routine.implementation_time.accurate_time.strftime('%H:%M') if routine.implementation_time.accurate_time %>
                  <% else %>
                    <%= routine.implementation_time.approximate_time %>
                  <% end %>
                  </span>
                </li>
                <li>
                  <span class="item-content-title"><b>頻度</b>:<%= routine.frequency.frequency_i18n %></span>&emsp;
                  <span class="item-content-title"><b>期間</b>:<%= routine.period.period_i18n %></span>
                </li>
              </ul>
              <%= image_tag "/level_#{routine.level}.jpg" %>
            </div>
          </div>
          <% end %>
          <% end %>
        </div>
      </div>
      <div class="pagenate_content">
        <%= paginate @routines %>
      </div>
      <!--バックナンバー-->
      <div>
        <div class="my-page-right-txt">
          <h5>■バックナンバー一覧</h5>
        </div>
        <div class="item-contents_all">
          <% @backnumber_routines.each do |routine| %>
          <%= link_to edit_admin_routine_path(routine.id) do %>
          <div class="item-old-contents">
            <div class="status_tag_routine">
              <%if routine.public_status %>
                <span class="item-check"><i class="fa-solid fa-lock-open"></i></span>
              <% else %>
                <span class="item-lock"><i class="fa-solid fa-lock"></i></span>
              <% end %>
            </div>
            <p class="create_at_tag"><%= l routine.created_at %></p>
            <div class="item-content">
              <ul>
                <li><b>目標</b><br><p><%= routine.target %></p></li>
                <li><b>ルーティン</b><br><p><%= routine.task.name %></p></li>
                <li class="sub_task_list">
                  <p>
                  <% routine.task.sub_tasks.each do | sub_task| %>
                    <span class="subtask_line"><%= sub_task.name %></span>
                  <% end %>
                  </p>
                </li>
                <li class="time-list">
                  <span class="item-content-title"><b>時間</b>:
                  <% if routine.implementation_time.accurate_time.present? %>
                    <%= routine.implementation_time.accurate_time.strftime('%H:%M') if routine.implementation_time.accurate_time %>
                  <% else %>
                    <%= routine.implementation_time.approximate_time %>
                  <% end %>
                  </span>
                </li>
                <li>
                  <span class="item-content-title"><b>頻度</b>:<%= routine.frequency.frequency_i18n %></span>&emsp;
                  <span class="item-content-title"><b>期間</b>:<%= routine.period.period_i18n %></span>
                </li>
              </ul>
              <%= image_tag "/level_#{routine.level}.jpg" %>
            </div>
          </div>
          <% end %>
          <% end %>
        </div>
      </div>
      <div class="pagenate_content">
        <%= paginate @routines %>
      </div>
    </div>
  </div>
</div>