config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'homes/top'
  end
    # 顧客用
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  devise_scope :customer do
    get '/customers', to: 'public/registrations#new'
  end
  # 管理者用
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
  root to: 'public/homes#top'
  scope module: :public do
    get '/about' => 'homes#about'
    get '/thanks' => 'homes#thanks'
    get '/privacy_policy' => 'homes#privacy'

    # 「customers」
    get '/customers/my_page' => 'customers#show', as: 'my_page'
    get '/customers/information/edit' => 'customers#edit', as: 'customers_edit'
    patch '/customers/information' => 'customers#update', as: 'information'
    get '/customers/unsubscribe' => 'customers#unsubscribe', as: 'unsubscribe'
    patch '/customers/withdraw' => 'customers#withdraw', as: 'withdraw'
    get '/routines/bookmark' => 'routines#like', as: 'bookmark'
    get '/routines/heatmap' => 'routines#heatmap'


    resources :routines do
      resources :sub_task_commits
      resources :task_commits
    end
    resources :bookmarks, only: [:create, :destroy, :index]

    resources :routines, except: [:index] do
      resource :bookmarks, only: [:create, :destroy, :index, :like]
    end


  end
  #####################
  # 管理者側のルーティング設定
  ## URLの頭に「admin」入れる設定
  namespace :admin do
    root to: 'homes#top'
    resources :routines, :customers

  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_flash_window.html.erb
<div class="flash-window flash-notice">
  <%= flash[:notice] %>
</div>
<div class="flash-window flash-error">
  <%= flash[:error] %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sasanqua</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/c1c2279c79.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= favicon_link_tag 'favicon.ico' %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons"/>
    <script type="text/javascript" src="https://d3js.org/d3.v3.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/cal-heatmap/3.3.10/cal-heatmap.min.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/cal-heatmap/3.3.10/cal-heatmap.css" />
  </head>

  <body>
    <div class="container">
      <header>
        <div class="outer">
          <div class="logo">
            <%= link_to root_path, style: "margin-right: auto" do %>
              <img src="/sazanka03.jpg">&ensp;<b>Sasanqua</b>
            <% end %>
          </div>
        </div>
        <!-- ハンバーガーメニュー部分 -->
        <div class="nav">
          <!-- ハンバーガーメニューの表示・非表示を切り替えるチェックボックス -->
          <input id="drawer_input" class="drawer_hidden" type="checkbox" />
          <label for="drawer_input" class="drawer_open"><span></span></label>
          <!--1.カスタマーログイン済み-->
          <% if customer_signed_in? %>
          <nav class="nav_content">
            <ul class="nav_list">
              <li class="nav_item"><%= link_to 'All routine' ,routines_path %></li>
              <li class="nav_item"><%= link_to 'About' ,about_path %></li>
              <li class="nav_item"><%= link_to 'MY' ,my_page_path %></li>
              <li class="nav_item"><%= link_to 'Log out' , destroy_customer_session_path, method: :delete %></li>
            </ul>
          </nav>
          <!--2.管理者ログイン済み-->
          <% elsif admin_signed_in? %>
          <nav class="nav_content">
            <ul class="nav_list">
              <li class="nav_item"><%= link_to '会員一覧' ,admin_customers_path %></li>
              <li class="nav_item"><%= link_to 'ルーティン一覧' ,admin_root_path,class:"under-line" %></li>
              <li class="nav_item"><%= link_to 'Log out' ,destroy_admin_session_path, method: :delete,class:"under-line" %></li>
            </ul>
          </nav>
          <!--3.未ログインユーザー-->
          <% else %>
          <nav class="nav_content">
            <ul class="nav_list">
              <li class="nav_item"><%= link_to 'About' ,about_path %></li>
              <% if request.fullpath.include? "/admin" %>
                <li class="nav_item"><%= link_to 'Log in', new_admin_session_path, class:"under-line" %></li>
              <% else %>
                <li class="nav_item"><%= link_to 'Sign up' ,new_customer_registration_path,class:"under-line" %></li>
                <li class="nav_item"><%= link_to 'Log in', new_customer_session_path, class:"under-line" %></li>
              <% end %>
            </ul>
          </nav>
          <% end %>
        </div>
      </header>
      <div class="flash-message">
        <%= render partial: 'layouts/flash_window' %>
      </div>
      
      <main>
        <%= yield %>
      </main>

      <footer>
        <nav class="nav_content_footer">
          <ul class="nav_list_footer">
            <li class="nav_item_footer">
            <%= link_to thanks_path do %>
              <i class="fa-solid fa-gift"></i>
            <% end %>
            </li>
            <li class="nav_item_footer">
            <%= link_to privacy_policy_path do %>
              <i class="fa-solid fa-shield-halved"></i>
            <% end %>
            </li>
            <li class="nav_item_footer">
              <a href="https://ysmynkk206.studio.site/" target = "_blank"><i class="fa-regular fa-address-card"></i></a>
            </li>
          </ul>
        </nav>
      </footer>
    </div>
  </body>
</html>